### ISSUE TITLE
'experiment/VOC/cls/infer/final/affx2,at_score,att2affx1/ann,affed/seed/2009_004108.png'

### ISSUE THREAD

**Issue by ChunmengLiu1** [HAL-42/FMA-WSSS#14]
Hi, thank you for the good job!

what's the file in 'experiment/VOC/cls/infer/final/affx2,at_score,att2affx1/ann,affed/seed/2009_004108.png'?
How can I get this file? I knowed that you provided but how to produce this kind of images? And what's the meaning of these images?

Thanks!

**Comment by ChunmengLiu1** [comment]
I solved the problem. Because it's wrong config file at this step: 
```
# Train classification task.
python src/tasks/train_coop/run.py -i 0 -e 0 -c configs/VOC/seg/cfg.py
```

It should be:
```
# Train classification task.
python src/tasks/train_coop/run.py -i 0 -e 0 -c configs/VOC/cls/cfg.py
```

**Comment by SSWS0803** [comment]
Nicely done 👍👍👍👍👍👍! This has solved a problem that has been bothering me for a while.

**Comment by HAL-42** [comment]
Fixed. Thank you very much for your reminder!
