### ISSUE TITLE
The files in experiments folder are all generated by running the code?

### ISSUE THREAD

**Issue by ChunmengLiu1** [HAL-42/FMA-WSSS#15]
Hi, thank you for the excellent job!
The files in experiments folder are all generated by running the code? Are there some stuff that are prior knowledge to help with the training. I feel confusion about this problem: "FileNotFoundError: [Errno 2] No such file or directory: 'experiment/VOC/cls/infer/final/affx2,at_score,att2affx1/ann,affed/seed/2009_004108.png'". But it didn't generate these files last step.
Thank you for your explain!
Best

**Comment by ChunmengLiu1** [comment]
I solved this issue, see [issue14](https://github.com/HAL-42/FMA-WSSS/issues/14)

**Comment by SSWS0803** [comment]
Nicely done 👍👍👍👍👍👍! This has solved a problem that has been bothering me for a while.

**Comment by chengfeng6s** [comment]
同样的问题

**Comment by HAL-42** [comment]
Fixed. Thanks @ChunmengLiu1
