### ISSUE TITLE
Generate SAM-based quasi-superpixel步骤出现问题

### ISSUE THREAD

**Issue by chengfeng6s** [HAL-42/FMA-WSSS#19]
你好，在这一步中
python src/tasks/sam_auto_seg/par_run.py --purge 1 -b 256 -w 50 -m uncompressed_rle -c configs/VOC/sams/cfg.py

我是运行下面的
CUDA_VISABLE_DEVICES=1,2 python src/tasks/sam_auto_seg/par_run.py --purge 1 -m uncompressed_rle -c configs/VOC/sams/cfg.py
然后出现了这样的警告，一直循环出现
![图片1](https://github.com/HAL-42/FMA-WSSS/assets/102983797/d1c9469d-edb2-4602-a171-232f1d472f33)
请问是什么问题，该怎么解决啊

**Comment by chengfeng6s** [comment]
我的GPU是多人共用的，难道说运行这个程序必须在GPU上不能有任何其他进程吗，请问这个问题该怎么解决呢

**Comment by HAL-42** [comment]
`src/tasks/sam_auto_seg/par_run.py`中39行，`_, env_with_current_cuda = allocate_cuda_by_group_rank(pkl_idx, 1, block=True, verbosity=True)`，`block`参数改为False即可。

**Comment by chengfeng6s** [comment]
好的，感谢回答！

**Comment by chengfeng6s** [comment]
好的，感谢回答！
