### ISSUE TITLE
seg_cls_labels.pkl文件没有

### ISSUE THREAD

**Issue by chengfeng6s** [HAL-42/FMA-WSSS#21]
你好，
![图片1](https://github.com/HAL-42/FMA-WSSS/assets/102983797/ddbc5d65-6ba8-4c3e-8173-8323c423aaf2)
可以提供下seg_cls_labels.pkl文件吗,数据集太大了，还没下载，这是用我已有的数据集跑的，但缺少这个文件

**Comment by HAL-42** [comment]
https://pan.baidu.com/s/1K4RPQXTdhvXwK4jzezsGpA?pwd=WSSS

**Comment by chengfeng6s** [comment]
感谢!
