### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/m2f_psudo/m2f-sl22-bt4-80k-512x-VOC.py'

### ISSUE THREAD

**Issue by chengfeng6s** [HAL-42/FMA-WSSS#26]
运行
# Train segmentation network with fine seed.
bash tools/dist_train.sh configs/m2f_psudo/m2f-sl22-bt4-100k-512x-COCO.py 2
出现
FileNotFoundError: [Errno 2] No such file or directory: 'configs/m2f_psudo/m2f-sl22-bt4-80k-512x-VOC.py'
这个配置文件好像没有，可以提供下mmsegmentation的完整目录内容吗

**Comment by kalpa61** [comment]
@chengfeng6s 你好，我也找不到这个文件，请问你找到这个配置文件在哪里了吗

**Comment by HAL-42** [comment]
See #30
